### ISSUE TITLE
[22:23:56] [Server thread/INFO]: [RageMode] Enabling RageMode v1.3.0.000

### ISSUE THREAD

**Issue by mastabaaudio** [montlikadani/RageMode#3]
### Describe your problem to what is
startup error
### Details
Plugin version: 
Software (Spigot/Bukkit etc.. `/version`) version: latest

### Console error
```
[22:23:56] [Server thread/INFO]: [RageMode] The 'config.yml' file successfully created!The 'arenas.yml' file successfully created!The 'rewards.yml' file successfully created!
[22:23:56] [Server thread/WARN]: java.lang.NullPointerException
[22:23:56] [Server thread/WARN]: 	at hu.montlikadani.ragemode.holder.HoloHolder.loadHolos(HoloHolder.java:62)
[22:23:56] [Server thread/WARN]: 	at hu.montlikadani.ragemode.holder.HoloHolder.initHoloHolder(HoloHolder.java:246)
[22:23:56] [Server thread/WARN]: 	at hu.montlikadani.ragemode.RageMode.onEnable(RageMode.java:104)
[22:23:56] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[22:23:56] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[22:23:56] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[22:23:56] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[22:23:56] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[22:23:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[22:23:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[22:23:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
[22:23:56] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
### Configuration file(s)
default

**Comment by montlikadani** [comment]
Fixed in [this commit](https://github.com/montlikadani/RageMode/commit/c5044faa0ec1120bc7482b14127afd3f06da53f2).
